# Generated by Django 5.1.4 on 2024-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR', max_length=100)),
                ('draw_offered_by', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('draw_accepted', models.BooleanField(default=False)),
                ('resign', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
    ]
