# Generated by Django 5.1.4 on 2024-12-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chessgame_pgn'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='increment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='initial_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='game_mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('rapid', 'Rapid'), ('blitz', 'Blitz'), ('bullet', 'Bullet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='game_over_reason',
            field=models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('threefold_repetition', 'Threefold repetition'), ('insufficient_material', 'Insufficient material'), ('fifty_moves', 'Fifty moves'), ('time_control', 'Time control'), ('resignation', 'Resignation'), ('draw_offer', 'Draw offer'), ('agreed_draw', 'Agreed draw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='initial_fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='moves',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='result',
            field=models.CharField(blank=True, default='*', max_length=10),
        ),
    ]
