# Generated by Django 5.1.4 on 2024-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chessgame_increment_chessgame_initial_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='event',
            field=models.CharField(default='Online game', max_length=50),
        ),
    ]
