# Generated by Django 5.1.4 on 2025-01-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chessgame_draw_offered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='current_turn',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
