# Generated by Django 5.1.4 on 2025-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chessgame_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='orientation',
            field=models.CharField(blank=True, default='white', max_length=10),
        ),
    ]
