# Generated by Django 5.1.4 on 2025-01-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chessgame_orientation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='current_turn',
            new_name='turn',
        ),
    ]
