# Generated by Django 5.1.4 on 2025-01-10 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_current_turn_chessgame_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='draw_accepted',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='draw_offered_by',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='resign',
        ),
        migrations.AddField(
            model_name='chessgame',
            name='game_over_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chessgame',
            name='game_over_type',
            field=models.CharField(blank=True, default='*', max_length=50),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='winner',
            field=models.CharField(blank=True, default='*', max_length=50),
        ),
    ]
